Django/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adm/', include('adm.urls')),
    path('', include('home.urls')),

]

import home

adm/urls.py
from django.urls import re_path

from . import views
app_name = 'adm'
urlpatterns = [
    re_path(r"^index/", views.index, name='index'),

    # 导航测试
    re_path(r"^navigation/", views.navigation, name='navigation'),
    re_path(r"^navigation_add/", views.navigation_add, name='navigation_add'),
    re_path(r"^get_navigation_list/", views.get_navigaton_list, name='get_navigation_list'),
    re_path(r'^navigation_edit/', views.navigation_edit, name='navigation_edit'),
    re_path(r'^navigation_del/$', views.navigation_del, name='navigation_del'),

    # 无限分类测试
    re_path(r'^cate/', views.cate, name='cate'),
    re_path(r"^cate_add/", views.cate_add, name='cate_add'),
    re_path(r"^cate_edit/", views.cate_edit, name='cate_edit'),
    re_path(r"^cate_del/", views.cate_del, name='cate_del'),


    # 菜单开发
    re_path(r'^menu/', views.menu, name='menu'),
    re_path(r'^menu_add/', views.menu_add, name='menu_add'),
    re_path(r'^menu_list/', views.menu_list, name='menu_list'),


    # 登陆注册
    re_path(r'^user_register/$', views.user_register, name='user_register'),
    re_path(r'^user_register_post/$', views.user_register_post, name='user_register_post'),



    re_path("setting/", views.setting, name='setting'),

]

adm/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Navigation(models.Model):
    n_title = models.CharField(max_length=20, null=False)
    # n_status = models.IntegerField(default=1)
    n_status = models.CharField(max_length=10, default='显示')
    n_sort = models.IntegerField(default=100)
    n_url = models.CharField(max_length=50, default='')


# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField(default=0)
    path = models.CharField(max_length=50)
    status = models.CharField(max_length=10, default='显示')


# 菜单管理
class Menu(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name='名称')
    pid = models.IntegerField(default=0, verbose_name='父级')
    path = models.CharField(max_length=50, verbose_name='路径')
    icon = models.CharField(max_length=100, default='&#xe62b;', verbose_name='图标')
    url = models.CharField(max_length=100, null=True, verbose_name='访问路由')
    status = models.CharField(max_length=10, choices=(('open', '开启'), ('close', '关闭')), default='open', verbose_name='状态')

    def __str__(self):
        return self.m_name

    class Meta:
        verbose_name = '系统菜单'
        verbose_name_plural = verbose_name
        db_table = 'adm_menu'



class UserProfile(models.Model):
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    email = models.CharField(max_length=50, default='', verbose_name='邮箱')
    password = models.CharField(max_length=100, default='', verbose_name='密码')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日前')
    gender = models.CharField(max_length=10, choices=(('male', '男'), ('female', '女')), default='male', verbose_name='性别')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        db_table = 'adm_userprofile'
        ordering = ['id']

adm/views.py
import time
from _md5 import md5
from audioop import reverse

from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, response
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from adm import models
from adm.models import Navigation, Cates, Menu, UserProfile
from adm.userfroms import UserRegisterForms
from lib import Helper
from lib.HttpCode import result

import json
from django.core import serializers
def index(request):
    return render(request, 'adm/index/index.html')


@xframe_options_exempt
def navigation(request):
    return render(request, 'adm/navigation/index.html')


@xframe_options_exempt
@csrf_exempt
def navigation_add(request):
    if request.method == 'GET':
        return render(request, 'adm/navigation/navigation_add.html')
    else:


        title = request.POST.get('title')
        print(title)
        sort = request.POST.get('sort')
        status = request.POST.get('status')
        url = request.POST.get('url')
        try:
            navigation = Navigation()
            navigation.n_title = title
            navigation.n_url = url
            if sort:
                navigation.n_sort = sort
            navigation.n_status = status
            navigation.save()
            data = {
                'code': 200,
                'msg': '添加成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '添加失败'
            }
            return JsonResponse(data)





def setting(request):
    return render(request, 'adm/setting/index.html')


def get_navigaton_list(request):
    data = {}
    json_data =[]
    nav_list = Navigation.objects.all()
    for nav in nav_list:
        data["id"] = nav.id
        data["title"] = nav.n_title
        json_data.append(data)

    return result(0, "ok", data=json.dumps(json_data))





@xframe_options_exempt
def get_navigaton_list(request):
    datas = models.Navigation.objects.all()
    dataCount = datas.count()
    req = request.POST
    list = []  # 存放所有的数据列表
    for data in datas:
        dict = {}  # 存放数据的字典
        dict["id"] = data.id
        dict["title"] = data.n_title
        dict["status"] = data.n_status
        dict["sort"] = data.n_sort
        dict["url"] = data.n_url
        list.append(dict)
    # print("列表",list)
    pageIndex = request.GET.get('page')  # pageIndex = request.POST.get('pageIndex')
    pageSize = request.GET.get('limit')  # pageSize = request.POST.get('pageSize')
    pageInator = Paginator(list, pageSize)
    contacts = pageInator.page(pageIndex)
    res = []  # 最终返回的结果集合
    for contact in contacts:
        # print(contact)
        res.append(contact)
    Result = {"code": 0, "Msg": "成功", "count": dataCount, "data": res}
    return JsonResponse(Result)


@xframe_options_exempt
@csrf_exempt
def navigation_edit(request):
    if request.method == 'GET':
        n_id = int(request.GET.get('id'))
        navigations = models.Navigation.objects.filter(id=n_id)
        for navigation in navigations:
            data = {
                'id': navigation.id,
                'title': navigation.n_title,
                'status': navigation.n_status,
                'sort': navigation.n_sort,
                'url': navigation.n_url
            }
        return render(request, 'adm/navigation/navigation_edit.html', context=data)
    else:
        title = request.POST.get('title')
        sort = request.POST.get('sort')
        status = request.POST.get('status')
        url = request.POST.get('url')
        n_id = request.POST.get('id')

        try:
            navigation = Navigation()
            navigation.n_title = title
            navigation.n_url = url
            if sort:
                navigation.n_sort = sort
            navigation.n_status = status
            navigation.id = n_id
            navigation.save()
            data = {
                'code': 200,
                'msg': '修改成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '修改失败'
            }
            return JsonResponse(data)


@require_POST
@csrf_exempt
def navigation_del(request):
    n_id = request.POST['n_id']
    try:
        navigation = Navigation.objects.get(id=n_id)
        navigation.delete()
        data = {
            'code': 200,
            'msg': '删除成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '删除失败'
        }
        return JsonResponse(data)


def navigation_add_post(request):
    return None


@xframe_options_exempt
def cate(request):
    catelist = get_cates_all(Cates)
    return render(request, 'adm/cate/index.html', context={'catelist': catelist})


@xframe_options_exempt
@csrf_exempt
def cate_add(request):
    if request.method == 'GET':

        catelist = get_cates_all(Cates)
        # 分配数据
        return render(request, 'adm/cate/cate_add.html', context={'catelist': catelist})
    else:
        c_name = request.POST.get('name')
        c_status = request.POST.get('status')

        c_pid = int(request.POST.get('pid'))

        if c_pid == 0:
            c_path = '0,'
        else:
            pob = Cates.objects.get(id=c_pid)
            c_path = str(pob.path) + str(c_pid) + ','
        try:
            cates = Cates()
            cates.name = c_name
            cates.pid = c_pid
            cates.status = c_status
            cates.path = c_path
            cates.save()
            data = {
                'code': 200,
                'msg': '添加成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '添加失败'
            }
            return JsonResponse(data)



# 封装函数.格式化获取分类数据
def get_cates_all(_model):
    # 获取所有的分类
    # data = Cates.objects.all()
    # select *,concat(path,id) as paths from myadmin_cates order by paths;
    model = _model
    data = model.objects.extra(select={'paths': 'concat(path,id)'}).order_by('paths')
    # 处理数据的顺序,缩进,及父级名
    for x in data:
        l = x.path.count(',')-1  # 0,1,2,
        x.sub = l*'|----'
        if x.pid == 0:
            x.pname = '顶级分类'
        else:
            pob = model.objects.get(id=x.pid)
            x.pname = pob.name
        # print(x.name,l)
    return data

@require_POST
@csrf_exempt
def cate_edit(request):
    c_name = request.POST.get('name')
    c_id = int(request.POST.get('id'))
    try:
        models.Cates.objects.filter(id=c_id).update(name=c_name)
        data = {
            'code': 200,
            'msg': '添加成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '添加失败'
        }
        return JsonResponse(data)


@require_POST
@csrf_exempt
def cate_del(request):
    c_id = request.POST['cid']
    try:
        # navigation = Navigation.objects.get(id=n_id)
        # navigation.delete()
        data = {
            'code': 200,
            'msg': '删除成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '删除失败'
        }
        return JsonResponse(data)




@xframe_options_exempt
@csrf_exempt
def menu(request):
    """
    # 菜单
    """
    # 分配数据
    return render(request, 'adm/menu/index.html')


@xframe_options_exempt
@csrf_exempt
def menu_add(request):
    if request.method == 'GET':

        catelist = get_cates_all(Menu)
        # 分配数据
        return render(request, 'adm/menu/menu_add.html', context={'catelist': catelist})
    else:
        m_name = request.POST.get('name')
        if m_name:
            m_status = request.POST.get('status')
            m_pid = int(request.POST.get('pid'))
            m_url = request.POST.get('url')
            m_icon = request.POST.get('icon')

            if m_pid == 0:
                m_path = '0,'
            else:
                pob = Menu.objects.get(id=m_pid)
                m_path = str(pob.path) + str(m_pid) + ','

            try:

                menu = Menu()
                menu.name = m_name
                menu.pid = m_pid
                menu.status = m_status
                menu.path = m_path
                menu.icon = m_icon
                menu.m_url = m_url
                menu.save()

                data = {
                    'code': 200,
                    'msg': '添加成功'
                }
                return JsonResponse(data)
            except:
                data = {
                    'code': 201,
                    'msg': '添加失败'
                }
                return JsonResponse(data)
        data = {
            'code': 201,
            'msg': '提交的信息有误'
        }
        return JsonResponse(data)


@xframe_options_exempt
@csrf_exempt
def menu_list(request):
    data = {}
    province = serializers.serialize("json", Menu.objects.all())
    data["data"] = json.loads(province)


    return JsonResponse(data, safe=False)




@xframe_options_exempt
@csrf_exempt
def user_register(request):
        return render(request, 'home/user/register.html')




@csrf_exempt
def user_register_post(request):

    user_register_forms = UserRegisterForms(request.POST)
    print(user_register_forms)
    if user_register_forms.is_valid():
        email = user_register_forms.cleaned_data['email']
        password = user_register_forms.cleaned_data['password']



        userlist = UserProfile.objects.filter(Q(name=email) | Q(email=email))

        if userlist:
            return render(request, 'home/user/register.html', {
                'msg': "用户已经存在"
            })

    else:
        return render(request, 'home/user/register.html', {

templates/adm/navigation/index.bak.html
{% include 'adm/meta.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'layui/dist/css/layui.css' %}">
<style>
    .layui-table-body{
    overflow-x:hidden;
    }

    .layui-table-body:hover{
    overflow-x:auto;
}
</style>
{% block content %}
    <table class="layui-hide" id="test"></table>
{% endblock %}
{% include 'adm/base_js.html' %}
<script>
    layui.use('table', function () {
        var table = layui.table;

        table.render({
            elem: '#test'
            , url: '{% url "adm:get_navigation_list" %}'
            , page: true
            , limit: 5
            , limits: [5, 15, 20]
            , cols: [[
                {field: 'id', title: 'ID', sort: true},
                {field: 'title', title: '名称'},
                {field: 'status', title: '状态'},
            ]]
            , page: true
        });
    });


</script>

templates/adm/navigation/index.html
{% include 'adm/meta.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'layui/dist/css/layui.css' %}">

{% block content %}
    <blockquote class="layui-elem-quote layui-text">
        <div class="layui-btn-group demoTable">
            <button class="layui-btn" data-type="getCheckData" >添加</button>
            <button class="layui-btn"> <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" >
       <i class="layui-icon">&#xe9aa;</i>
    </a></button>
        </div>
    </blockquote>
    <table class="layui-table"
           lay-data="{ height:500, url:'{% url "adm:get_navigation_list" %}', page:true, id:'idTest'}"
           lay-filter="demo">
        <thead>
        <tr>
            <th lay-data="{type:'checkbox', fixed: 'left'}"></th>
            <th lay-data="{field:'id', sort: true, fixed: true}">ID</th>
            <th lay-data="{field:'title'}">名称</th>
            <th lay-data="{field:'url'}">URL</th>
            <th lay-data="{field:'status', sort: true}">状态</th>
            <th lay-data="{field:'sort'}">排序</th>
            <th lay-data="{fixed: 'right', width:178, align:'center', toolbar: '#barDemo'}">操作</th>
        </tr>
        </thead>
    </table>

    <script type="text/html" id="barDemo">
        {#        <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">查看</a>#}
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>

    </script>



{% endblock %}
{% include 'adm/base_js.html' %}

<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
    layui.use('table', function () {
        var table = layui.table;
        //监听表格复选框选择
        table.on('checkbox(demo)', function (obj) {
            console.log(obj)
        });
        //监听工具条
        table.on('tool(demo)', function (obj) {
            var data = obj.data;
            if (obj.event === 'detail') {
                layer.msg('ID：' + data.id + ' 的查看操作');
            } else if (obj.event === 'del') {
                layer.confirm('确定删除导航<span style="color:red"> &nbsp;' + data.title + '</span>&nbsp;吗？', {
                    btn: ['是', '否'] //按钮
                }, function () {
                    $.ajax({
                        url: '{% url "adm:navigation_del" %}',
                        type: "POST",
                        data: {"n_id": data.id},
                        success: function (e) {
                            console.log(e.code)
                            if (e.code == 200) {
                                 layer.msg("删除成功", {
                                    icon: 1,
                                    time: 1000,
                                    end: function () {
                                        window.location.reload()
                                        {#parent.location.reload();#}
                                    }
                                 })
                            } else {
                                layer.msg(e.msg);
                            }
                        },
                    })
                })
            } else if (obj.event === 'edit') {
                layer.open({
                    type: 2,
                    skin: 'layui-layer-demo', //样式类名
                    closeBtn: 1, //不显示关闭按钮
                    anim: 3,
                    title: "首页导航修改",
                    area: ['60%', '45%'], //宽高
                    shadeClose: true, //开启遮罩关闭
                    content: 'http://127.0.0.1:8000/adm/navigation_edit/?id=' + data.id //待更改，域名应替换为变量
                });
            }
        });

        var $ = layui.$, active = {
            getCheckData: function () { //获取选中数据
                layer.open({
                    type: 2,
                    skin: 'layui-layer-demo', //样式类名
                    closeBtn: 1, //不显示关闭按钮
                    anim: 3,
                    title: "首页导航添加",
                    area: ['60%', '45%'], //宽高
                    shadeClose: true, //开启遮罩关闭
                    content: 'http://127.0.0.1:8000/adm/navigation_add/'
                });
            },
        };

        $('.demoTable .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>
<script>


    {#    #}
    {#    layui.use('table', function () {#}
    {#        var table = layui.table;#}
    {##}
    {#        table.render({#}
    {#            elem: '#test'#}
    {#            , url: '{% url "adm:get_navigation_list" %}'#}
    {#            , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板#}
    {#,toolbar: 'default' //开启工具栏，此处显示默认图标，可以自定义模板，详见文档#}
    {#            , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可#}
    {#                title: '提示'#}
    {#                , layEvent: 'LAYTABLE_TIPS'#}
    {#                , icon: 'layui-icon-tips'#}
    {#            }]#}
    {#            , title: '用户数据表'#}
    {#            , cols: [[#}
    {#                {type: 'checkbox', fixed: 'left'}#}
    {#                , {field: 'id', title: 'ID', fixed: 'left', unresize: true, sort: true}#}
    {#                , {field: 'title', title: '名称', edit: 'text'}#}
    {#                , {field: 'status', sort: true, templet: '#sexTpl'}#}
    {#                , {field: 'sort', title: '排序', edit: 'text', unresize: true, sort: true}#}
    {#                , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 150}#}
    {#            ]]#}
    {#            , page: true#}
    {#        });#}
    {#        //监听头工具栏事件#}
    {#        table.on('toolbar(test)', function (obj) {#}
    {#            var checkStatus = table.checkStatus(obj.config.id)#}
    {#                , data = checkStatus.data; //获取选中的数据#}
    {##}
    {#            switch (obj.event) {#}
    {#                case 'add':#}
    {#                    layer.open({#}
    {#                        type: 2,#}
    {#                        skin: 'layui-layer-demo', //样式类名#}
    {#                        closeBtn: 1, //不显示关闭按钮#}
    {#                        anim: 3,#}
    {#                        title: "首页导航添加",#}
    {#                        area: ['30%', '45%'], //宽高#}
    {#                        shadeClose: true, //开启遮罩关闭#}
    {#                        content: 'http://127.0.0.1:8000/adm/navigation_add/'#}
    {#                    });#}
    {#                    break;#}
    {#                case 'update':#}
    {#                    if (data.length === 0) {#}
    {#                        layer.msg('请选择一行');#}
    {#                    } else if (data.length > 1) {#}
    {#                        layer.msg('只能同时编辑一个');#}
    {#                    } else {#}
    {#                        layer.alert('编辑 [id]：' + checkStatus.data[0].id);#}
    {#                    }#}
    {#                    break;#}
    {#                case 'delete':#}
    {#                    if (data.length === 0) {#}
    {#                        layer.msg('请选择一行');#}
    {#                    } else {#}
    {#                        layer.msg('删除');#}
    {#                    }#}
    {#                    break;#}
    {#            }#}
    {#            ;#}
    {##}
    {##}
    {#        });#}
    {#        //监听行工具事件#}
    {#        table.on('toolbar(test)', function (obj) {#}
    {#            var checkStatus = table.checkStatus(obj.config.id);#}
    {#            switch (obj.event) {#}
    {#                case 'nav_add':#}
    {#                    layer.open({#}
    {#                        type: 2,#}
    {#                        skin: 'layui-layer-demo', //样式类名#}
    {#                        closeBtn: 1, //不显示关闭按钮#}
    {#                        anim: 3,#}
    {#                        title: "首页导航添加",#}
    {#                        area: ['30%', '45%'], //宽高#}
    {#                        shadeClose: true, //开启遮罩关闭#}
    {#                        content: 'http://127.0.0.1:8000/adm/navigation_add/'#}
    {#                    });#}
    {#                    break;#}
    {#                case 'getCheckLength':#}
    {#                    var data = checkStatus.data;#}
    {#                    layer.msg('选中了：' + data.length + ' 个');#}
    {#                    break;#}
    {#                case 'isAll':#}
    {#                    layer.msg(checkStatus.isAll ? '全选' : '未全选');#}
    {#                    break;#}
    {##}
    {#                //自定义头工具栏右侧图标 - 提示#}
    {#                case 'LAYTABLE_TIPS':#}
    {#                    layer.alert('这是工具栏右侧自定义的一个图标按钮');#}
    {#                    break;#}
    {#            }#}
    {#            ;#}
    {#        });#}
    {##}
    {#        //监听行工具事件#}
    {#        table.on('tool(test)', function (obj) {#}
    {#            var data = obj.data;#}
    {#            //console.log(obj)#}
    {#            if (obj.event === 'del') {#}
    {#                layer.confirm('真的删除行么', function (index) {#}
    {#                    obj.del();#}
    {#                    layer.close(index);#}
    {#                });#}
    {#            } else if (obj.event === 'edit') {#}
    {#                layer.prompt({#}
    {#                    formType: 2#}
    {#                    , value: data.email#}
    {#                }, function (value, index) {#}
    {#                    obj.update({#}
    {#                        email: value#}
    {#                    });#}
    {#                    layer.close(index);#}
    {#                });#}
    {#            }#}
    {##}
    {#        });#}
    {#    });#}
    {#    #}
</script>

templates/adm/navigation/navigation_add.html
{% include 'adm/meta.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'layui/dist/css/layui.css' %}">
<form style="margin-top: 2em" class="layui-form layui-form-pane" method="post" id="fm">
    {% csrf_token %}
    <div class="layui-form-item">
        <label class="layui-form-label">名称</label>
        <div class="layui-input-inline">
            <input type="text" name="title" required="required" placeholder="请输入" autocomplete="off"
                   class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">URL</label>
        <div class="layui-input-inline">
            <input type="text" name="url" lay-verify="required" placeholder="请输入" autocomplete="off"
                   class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">排序</label>
        <div class="layui-input-inline">
            <input type="text" name="sort" lay-verify="required" placeholder="请输入" autocomplete="off"
                   class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">状态</label>
        <div class="layui-input-block">
            <input type="radio" name="status" value="显示" title="显示" checked="">
            <div class="layui-unselect layui-form-radio layui-form-radioed"><i class="layui-anim layui-icon"></i>
                <div>显示</div>
            </div>
            <input type="radio" name="status" value="隐藏" title="隐藏">
            <div class="layui-unselect layui-form-radio"><i class="layui-anim layui-icon"></i>
                <div>隐藏</div>
            </div>
        </div>
    </div>
    <div class="layui-form-item" style="text-align: right;margin-bottom: 2em">
        <button type="button" class="layui-btn" id="btn">提交</button>
    </div>
</form>


{% include 'adm/base_js.html' %}

<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
    $(function () {
        $('#btn').click(function () {
            $.ajax({
                url: '{% url "adm:navigation_add" %}',
                type: 'POST',
                dataType: 'JSON',
                data: $('#fm').serialize(),
                success: function (e) {
                    console.log(e)
                    if (e.code == 200) {

                        layer.msg(e.msg, {
                            icon: 1,
                            time: 1000,
                            end: function () {
                                layer.confirm('是否继续添加', {
                                    btn: ['是', '否'] //按钮
                                }, function () {
                                    window.location.reload()
                                }, function () {
                                     parent.location.reload()
                                });
                            }
                        })

                    } else {
                        layer.msg(e.msg, {icon: 2});
                    }
                }
            })
        })
    })

     layui.use('table', function () {
        var table = layui.table;
        //监听表格复选框选择
        $('.demoTable .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
</script>

templates/adm/navigation/navigation_edit.html
{% include 'adm/meta.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'layui/dist/css/layui.css' %}">
<form style="margin-top: 2em" class="layui-form layui-form-pane" id="fm">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ id }}">
    <div class="layui-form-item">
        <label class="layui-form-label">名称</label>
        <div class="layui-input-inline">
            <input type="text" name="title" lay-verify="required" value="{{ title }}" placeholder="请输入"
                   autocomplete="off" class="layui-input">
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">URL</label>
            <div class="layui-input-inline">
                <input type="text" name="url" lay-verify="required" value="{{ url }}" placeholder="请输入"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">排序</label>
            <div class="layui-input-inline">
                <input type="text" name="sort" lay-verify="required" placeholder="请输入" autocomplete="off"
                       class="layui-input" value="{{ sort }}">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-block">
                <input type="radio" name="status" value="显示" title="显示" {% if  status == "显示" %}
                       checked="selected" {% endif %}>
                <div class="layui-unselect layui-form-radio layui-form-radioed"><i class="layui-anim layui-icon"></i>
                    <div>显示</div>
                </div>
                <input type="radio" name="status" value="隐藏" title="隐藏" {% if  status == "隐藏" %}
                       checked="selected" {% endif %}>
                <div class="layui-unselect layui-form-radio"><i class="layui-anim layui-icon"></i>
                    <div>隐藏</div>
                </div>
            </div>
        </div>

        <div class="layui-form-item" style="text-align: right;margin-bottom: 2em">
            <button class="layui-btn" lay-submit="" id="btn" lay-filter="demo2">提交</button>
        </div>
</form>


{% include 'adm/base_js.html' %}

<!-- 注意：如果你直接复制所有代码到本地，上述js路径需要改成你本地的 -->
<script>
    $(function () {
        $('#btn').click(function () {
            $.ajax({
                url: '{% url "adm:navigation_edit" %}',
                type: 'POST',
                dataType: 'JSON',
                data: $('#fm').serialize(),
                success: function (e) {
                    layer.msg(e.code, {time: 1000});
                    if (e.code == 200) {
                        parent.location.reload();
                    } else {
                        layer.msg(e.msg);
                    }
                }
            })
        })
    })

    layui.use('table', function () {
        var table = layui.table;
        //监听表格复选框选择
        $('.demoTable .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });

</script>