Django/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adm/', include('adm.urls')),
    path('', include('home.urls')),

]

import home

adm/urls.py
from django.urls import re_path

from . import views
app_name = 'adm'
urlpatterns = [
    re_path(r"^index/", views.index, name='index'),

    # 导航测试
    re_path(r"^navigation/", views.navigation, name='navigation'),
    re_path(r"^navigation_add/", views.navigation_add, name='navigation_add'),
    re_path(r"^get_navigation_list/", views.get_navigaton_list, name='get_navigation_list'),
    re_path(r'^navigation_edit/', views.navigation_edit, name='navigation_edit'),
    re_path(r'^navigation_del/$', views.navigation_del, name='navigation_del'),

    # 无限分类测试
    re_path(r'^cate/', views.cate, name='cate'),
    re_path(r"^cate_add/", views.cate_add, name='cate_add'),
    re_path(r"^cate_edit/", views.cate_edit, name='cate_edit'),
    re_path(r"^cate_del/", views.cate_del, name='cate_del'),


    # 菜单开发
    re_path(r'^menu/', views.menu, name='menu'),
    re_path(r'^menu_add/', views.menu_add, name='menu_add'),
    re_path(r'^menu_list/', views.menu_list, name='menu_list'),


    # 登陆注册
    re_path(r'^user_register/$', views.user_register, name='user_register'),
    re_path(r'^user_register_post/$', views.user_register_post, name='user_register_post'),



    re_path("setting/", views.setting, name='setting'),

]

adm/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Navigation(models.Model):
    n_title = models.CharField(max_length=20, null=False)
    # n_status = models.IntegerField(default=1)
    n_status = models.CharField(max_length=10, default='显示')
    n_sort = models.IntegerField(default=100)
    n_url = models.CharField(max_length=50, default='')


# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField(default=0)
    path = models.CharField(max_length=50)
    status = models.CharField(max_length=10, default='显示')


# 菜单管理
class Menu(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name='名称')
    pid = models.IntegerField(default=0, verbose_name='父级')
    path = models.CharField(max_length=50, verbose_name='路径')
    icon = models.CharField(max_length=100, default='&#xe62b;', verbose_name='图标')
    url = models.CharField(max_length=100, null=True, verbose_name='访问路由')
    status = models.CharField(max_length=10, choices=(('open', '开启'), ('close', '关闭')), default='open', verbose_name='状态')

    def __str__(self):
        return self.m_name

    class Meta:
        verbose_name = '系统菜单'
        verbose_name_plural = verbose_name
        db_table = 'adm_menu'



class UserProfile(models.Model):
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    email = models.CharField(max_length=50, default='', verbose_name='邮箱')
    password = models.CharField(max_length=100, default='', verbose_name='密码')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日前')
    gender = models.CharField(max_length=10, choices=(('male', '男'), ('female', '女')), default='male', verbose_name='性别')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        db_table = 'adm_userprofile'
        ordering = ['id']

adm/views.py
import time
from _md5 import md5
from audioop import reverse

from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, response
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from adm import models
from adm.models import Navigation, Cates, Menu, UserProfile
from adm.userfroms import UserRegisterForms
from lib import Helper
from lib.HttpCode import result

import json
from django.core import serializers
def index(request):
    return render(request, 'adm/index/index.html')


@xframe_options_exempt
def navigation(request):
    return render(request, 'adm/navigation/index.html')


@xframe_options_exempt
@csrf_exempt
def navigation_add(request):
    if request.method == 'GET':
        return render(request, 'adm/navigation/navigation_add.html')
    else:


        title = request.POST.get('title')
        print(title)
        sort = request.POST.get('sort')
        status = request.POST.get('status')
        url = request.POST.get('url')
        try:
            navigation = Navigation()
            navigation.n_title = title
            navigation.n_url = url
            if sort:
                navigation.n_sort = sort
            navigation.n_status = status
            navigation.save()
            data = {
                'code': 200,
                'msg': '添加成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '添加失败'
            }
            return JsonResponse(data)





def setting(request):
    return render(request, 'adm/setting/index.html')


def get_navigaton_list(request):
    data = {}
    json_data =[]
    nav_list = Navigation.objects.all()
    for nav in nav_list:
        data["id"] = nav.id
        data["title"] = nav.n_title
        json_data.append(data)

    return result(0, "ok", data=json.dumps(json_data))





@xframe_options_exempt
def get_navigaton_list(request):
    datas = models.Navigation.objects.all()
    dataCount = datas.count()
    req = request.POST
    list = []  # 存放所有的数据列表
    for data in datas:
        dict = {}  # 存放数据的字典
        dict["id"] = data.id
        dict["title"] = data.n_title
        dict["status"] = data.n_status
        dict["sort"] = data.n_sort
        dict["url"] = data.n_url
        list.append(dict)
    # print("列表",list)
    pageIndex = request.GET.get('page')  # pageIndex = request.POST.get('pageIndex')
    pageSize = request.GET.get('limit')  # pageSize = request.POST.get('pageSize')
    pageInator = Paginator(list, pageSize)
    contacts = pageInator.page(pageIndex)
    res = []  # 最终返回的结果集合
    for contact in contacts:
        # print(contact)
        res.append(contact)
    Result = {"code": 0, "Msg": "成功", "count": dataCount, "data": res}
    return JsonResponse(Result)


@xframe_options_exempt
@csrf_exempt
def navigation_edit(request):
    if request.method == 'GET':
        n_id = int(request.GET.get('id'))
        navigations = models.Navigation.objects.filter(id=n_id)
        for navigation in navigations:
            data = {
                'id': navigation.id,
                'title': navigation.n_title,
                'status': navigation.n_status,
                'sort': navigation.n_sort,
                'url': navigation.n_url
            }
        return render(request, 'adm/navigation/navigation_edit.html', context=data)
    else:
        title = request.POST.get('title')
        sort = request.POST.get('sort')
        status = request.POST.get('status')
        url = request.POST.get('url')
        n_id = request.POST.get('id')

        try:
            navigation = Navigation()
            navigation.n_title = title
            navigation.n_url = url
            if sort:
                navigation.n_sort = sort
            navigation.n_status = status
            navigation.id = n_id
            navigation.save()
            data = {
                'code': 200,
                'msg': '修改成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '修改失败'
            }
            return JsonResponse(data)


@require_POST
@csrf_exempt
def navigation_del(request):
    n_id = request.POST['n_id']
    try:
        navigation = Navigation.objects.get(id=n_id)
        navigation.delete()
        data = {
            'code': 200,
            'msg': '删除成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '删除失败'
        }
        return JsonResponse(data)


def navigation_add_post(request):
    return None


@xframe_options_exempt
def cate(request):
    catelist = get_cates_all(Cates)
    return render(request, 'adm/cate/index.html', context={'catelist': catelist})


@xframe_options_exempt
@csrf_exempt
def cate_add(request):
    if request.method == 'GET':

        catelist = get_cates_all(Cates)
        # 分配数据
        return render(request, 'adm/cate/cate_add.html', context={'catelist': catelist})
    else:
        c_name = request.POST.get('name')
        c_status = request.POST.get('status')

        c_pid = int(request.POST.get('pid'))

        if c_pid == 0:
            c_path = '0,'
        else:
            pob = Cates.objects.get(id=c_pid)
            c_path = str(pob.path) + str(c_pid) + ','
        try:
            cates = Cates()
            cates.name = c_name
            cates.pid = c_pid
            cates.status = c_status
            cates.path = c_path
            cates.save()
            data = {
                'code': 200,
                'msg': '添加成功'
            }
            return JsonResponse(data)
        except:
            data = {
                'code': 201,
                'msg': '添加失败'
            }
            return JsonResponse(data)



# 封装函数.格式化获取分类数据
def get_cates_all(_model):
    # 获取所有的分类
    # data = Cates.objects.all()
    # select *,concat(path,id) as paths from myadmin_cates order by paths;
    model = _model
    data = model.objects.extra(select={'paths': 'concat(path,id)'}).order_by('paths')
    # 处理数据的顺序,缩进,及父级名
    for x in data:
        l = x.path.count(',')-1  # 0,1,2,
        x.sub = l*'|----'
        if x.pid == 0:
            x.pname = '顶级分类'
        else:
            pob = model.objects.get(id=x.pid)
            x.pname = pob.name
        # print(x.name,l)
    return data

@require_POST
@csrf_exempt
def cate_edit(request):
    c_name = request.POST.get('name')
    c_id = int(request.POST.get('id'))
    try:
        models.Cates.objects.filter(id=c_id).update(name=c_name)
        data = {
            'code': 200,
            'msg': '添加成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '添加失败'
        }
        return JsonResponse(data)


@require_POST
@csrf_exempt
def cate_del(request):
    c_id = request.POST['cid']
    try:
        # navigation = Navigation.objects.get(id=n_id)
        # navigation.delete()
        data = {
            'code': 200,
            'msg': '删除成功'
        }
        return JsonResponse(data)
    except:
        data = {
            'code': 201,
            'msg': '删除失败'
        }
        return JsonResponse(data)




@xframe_options_exempt
@csrf_exempt
def menu(request):
    """
    # 菜单
    """
    # 分配数据
    return render(request, 'adm/menu/index.html')


@xframe_options_exempt
@csrf_exempt
def menu_add(request):
    if request.method == 'GET':

        catelist = get_cates_all(Menu)
        # 分配数据
        return render(request, 'adm/menu/menu_add.html', context={'catelist': catelist})
    else:
        m_name = request.POST.get('name')
        if m_name:
            m_status = request.POST.get('status')
            m_pid = int(request.POST.get('pid'))
            m_url = request.POST.get('url')
            m_icon = request.POST.get('icon')

            if m_pid == 0:
                m_path = '0,'
            else:
                pob = Menu.objects.get(id=m_pid)
                m_path = str(pob.path) + str(m_pid) + ','

            try:

                menu = Menu()
                menu.name = m_name
                menu.pid = m_pid
                menu.status = m_status
                menu.path = m_path
                menu.icon = m_icon
                menu.m_url = m_url
                menu.save()

                data = {
                    'code': 200,
                    'msg': '添加成功'
                }
                return JsonResponse(data)
            except:
                data = {
                    'code': 201,
                    'msg': '添加失败'
                }
                return JsonResponse(data)
        data = {
            'code': 201,
            'msg': '提交的信息有误'
        }
        return JsonResponse(data)


@xframe_options_exempt
@csrf_exempt
def menu_list(request):
    data = {}
    province = serializers.serialize("json", Menu.objects.all())
    data["data"] = json.loads(province)


    return JsonResponse(data, safe=False)




@xframe_options_exempt
@csrf_exempt
def user_register(request):
        return render(request, 'home/user/register.html')




@csrf_exempt
def user_register_post(request):

    user_register_forms = UserRegisterForms(request.POST)
    print(user_register_forms)
    if user_register_forms.is_valid():
        email = user_register_forms.cleaned_data['email']
        password = user_register_forms.cleaned_data['password']



        userlist = UserProfile.objects.filter(Q(name=email) | Q(email=email))

        if userlist:
            return render(request, 'home/user/register.html', {
                'msg': "用户已经存在"
            })

    else:
        return render(request, 'home/user/register.html', {

templates/adm/adm_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
        {% include 'adm/meta.html' %}
    {% endblock %}
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    {% block header %}
        {% include 'adm/header.html' %}
    {% endblock %}
    {% block menu %}
        {% include 'adm/menu.html' %}
    {% endblock %}

    <!--tab标签-->
    <div class="layui-tab" lay-filter="demo" lay-allowclose="true" style="margin-left: 200px;">
        <ul class="layui-tab-title"></ul>
        <div class="layui-tab-content">
             {% block content %}
             {% endblock %}
        </div>

    </div>
{% include 'adm/footer.html' %}
</div>
{% include 'adm/base_js.html' %}
<script>
layui.use('element', function(){
  var element = layui.element; //导航的hover效果、二级菜单等功能，需要依赖element模块

  //监听导航点击
  element.on('nav(demo)', function(elem){
    //console.log(elem)
    layer.msg(elem.text());
  });
});
</script>
</body>
</html>

templates/adm/base_js.html
{% load static %}
    <script src="{% static 'adm/lib/jquery/1.9.1/jquery.js' %}"></script>
    <script src="{% static 'layui/src/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'adm/adm/js/base.js' %}"></script>

templates/adm/footer.html
{#<div class="layui-footer" style="text-align:center;">#}
{#    <!-- 底部固定区域 -->#}
{#    © sunway.tk XXXX业务管理平台#}
{#</div>#}

templates/adm/header.html
 <div class="layui-header">
        <div class="layui-logo" aria-colspan="5">Python Django</div>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                欢迎光临，刘英伟
            </li>
            <li class="layui-nav-item"><a href="">安全退出</a></li>
        </ul>
    </div>

templates/adm/menu.html
<div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧垂直导航区域-->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item">
                    <a class="" href="javascript:;">基本设置</a>
                    <dl class="layui-nav-child">
                        <dd>
                            <a href="javascript:;" data-id="1" data-title="首页导航" data-url="{% url 'adm:navigation' %}" class="site-demo-active" data-type="tabAdd">首页导航</a></dd>
                    </dl>
                     <dl class="layui-nav-child">
                        <dd>
                            <a href="javascript:;" data-id="2" data-title="无限分类" data-url="{% url 'adm:cate' %}" class="site-demo-active" >无限分类</a></dd>
                    </dl>
                </li>
            </ul>

            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item">
                    <a class="" href="javascript:;">权限管理</a>
                    <dl class="layui-nav-child">
                        <dd>
                            <a href="javascript:;" data-id="3" data-title="菜单管理" data-url="{% url 'adm:menu' %}" class="site-demo-active" >菜单管理</a></dd>
                    </dl>
                </li>
            </ul>

        </div>
    </div>

templates/adm/meta.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>{{ title }} Python Django 后台管理</title>
<link rel="stylesheet" href="{% static 'layui/src/css/layui.css' %}">

templates/adm/reload.html
<button class="layui-btn" data-type="reload"><i class="layui-icon">&#xe9aa;</i></button>
<script>
    layui.use('table', function () {
        var table = layui.table;
        var $ = layui.$, active = {
            reload: function () {
                window.location.reload()
            }
        };
    });
</script>